#项目配置文件
spring:
  mvc:
    view:
      suffix: .html
    static-path-pattern: /**

#生成授权文件所需要的配置
mbblicense:
  server:
    resource: D:\file\授权文件\serverKeys.store
    storePwd: storeKeys2020
    alias: serverKey
    keyPwd: serverKey2020
    subject: mbblicense
    licPath: D:\file\授权文件\license.lic
    
