spring:
  application:
    name: mbb

server:
  port: 8088

mbblicense:
  client:
    resource: C:/Users/马冰冰/Desktop/绝对路径/clientKeys.store
    storePwd: storeKeys2020
    alias: clientKey
    subject: mbblicense
    licPath: C:/Users/马冰冰/Desktop/绝对路径/license.lic
    debugger: true